### PR TITLE
Incorrect Login Credentials Unhandled Exception

### LINKED ISSUE #55: Faliure to login results in an unhandled exception
**Description**
When sending a post request to the login page (`/identity/api/auth/login`), bad credentials result in an exception raised (From springframework?), in function `authenticateUser` (Raised from calling `authenticateUserLogin`)

One more issue is that you actually mean to return `500` for an unsuccessful login. i.e

`return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(jwtToken);`

Which doesn't make much sense, but is never reached anyways. The `500` actually derives from an exception, and you have no control over it.

You should wrap the `JwtResponse` in a try/catch block, and return an `HttpStatus.UNAUTHORIZED` response accordingly. You also have a string for bad credentials so better use that in the response.

**To Reproduce**
Send a POST request to `/identity/api/auth/login` with fake credentials

**Expected behavior**
An `403` or `401` should've been returned by you and not by an exception raised from the authentication management library.

**Runtime Environment**
Docker version 20.10.12, build e91ed57
Linux 5.14.0-1033-oem #36-Ubuntu SMP Mon Apr 4 15:15:49 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by mathew-jose**
## Description
Pull request to fix #55. An incorrect login attempt will now result in a response of `401`.

### Testing
Tested with incorrect email ID and an incorrect password and verified the return status code.

### Checklist:
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged
- [x] I have documented any changes if required in the [docs](docs).

### CODE REVIEW

File: services/identity/src/main/java/com/crapi/controller/AuthController.java [hunk 1]
```diff
@@ -48,11 +49,19 @@ public class AuthController {
...
+            
+            if(jwtToken.getToken() != null) {
+                return ResponseEntity.status(HttpStatus.OK).body(jwtToken);
+            }
+            else {
+                return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(jwtToken);
+            }
+
+        } catch (BadCredentialsException e) {
+            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(new JwtResponse("",UserMessage.INVALID_CREDENTIALS));
```
Comment (piyushroshan) [inline services/identity/src/main/java/com/crapi/controller/AuthController.java:64]: Instead of try catch we should handle the null scenario of JWT token.

Comment (mathew-jose) [reply services/identity/src/main/java/com/crapi/controller/AuthController.java:64]: The if block checking for the null condition of the JWT token is part of the try block.

**Review by piyushroshan — APPROVED** [review]

**Review by piyushroshan — CHANGES_REQUESTED** [review]
Add unit test for this

**Review by piyushroshan — APPROVED** [review]
